/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 SoccerField.gltf --transform 
Files: SoccerField.gltf [6.55KB] > /Users/ale/Clients/react-futbol/src/gltf_exports/SoccerField-transformed.glb [5.59KB] (15%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function SoccerField(props) {
  const { nodes, materials } = useGLTF('/SoccerField-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.174, -32.177]} rotation={[-Math.PI, 0, -Math.PI]} scale={[2.639, 1.033, 1.417]}>
        <mesh geometry={nodes.Cube006.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Net} />
      </group>
      <mesh geometry={nodes.Soccer_Field.geometry} material={materials.Green} position={[0, 0.001, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[9.311, 1, 5.288]} />
    </group>
  )
}

// useGLTF.preload('/SoccerField-transformed.glb')
